name: CD - Deploy em produção

on:
  # Gatilho Inteligente: Só liga quando a esteira "CI" terminar
  workflow_run:
    workflows: ["CI - Code Quality & Security"]
    types:
      - completed

jobs:
  deploy:
    name: Atualizar Servidor e Reiniciar
    runs-on: self-hosted
    # Trava de Segurança Final: Só roda se o CI passou (ficou verde)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Puxar o código mais recente
        uses: actions/checkout@v4

      - name: Criar arquivo .env automaticamente
        # 1. Declaramos os segredos de forma segura aqui:
        env:
          ENV_FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
          ENV_DB_USER: ${{ secrets.DB_USER }}
          ENV_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ENV_DB_HOST: ${{ secrets.DB_HOST }}
          ENV_DB_PORT: ${{ secrets.DB_PORT }}
          ENV_DB_NAME: ${{ secrets.DB_NAME }}
          ENV_MAIL_SERVER: ${{ secrets.MAIL_SERVER }}
          ENV_MAIL_PORT: ${{ secrets.MAIL_PORT }}
          ENV_MAIL_USE_TLS: ${{ secrets.MAIL_USE_TLS }}
          ENV_MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          ENV_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        # 2. Lemos de forma nativa no bash usando o '$'
        run: |
          echo "FLASK_SECRET_KEY=$ENV_FLASK_SECRET_KEY" > .env
          echo "DB_USER=$ENV_DB_USER" >> .env
          echo "DB_PASSWORD=$ENV_DB_PASSWORD" >> .env
          echo "DB_HOST=$ENV_DB_HOST" >> .env
          echo "DB_PORT=$ENV_DB_PORT" >> .env
          echo "DB_NAME=$ENV_DB_NAME" >> .env
          echo "MAIL_SERVER=$ENV_MAIL_SERVER" >> .env
          echo "MAIL_PORT=$ENV_MAIL_PORT" >> .env
          echo "MAIL_USE_TLS=$ENV_MAIL_USE_TLS" >> .env
          echo "MAIL_USERNAME=$ENV_MAIL_USERNAME" >> .env
          echo "MAIL_PASSWORD=$ENV_MAIL_PASSWORD" >> .env

      - name: Preparar Ambiente Virtual e Dependências
        run: |
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install -r requirements.txt
          pip install gunicorn
      
      - name: Ajustar Permissões para o usuário trap
        run: |
          sudo chown -R trap:trap .
      
      - name: Reiniciar o serviço da aplicação
        run: |
          sudo /usr/bin/systemctl restart ia-sdlc.service