name: CD - Deploy em produção

on:
  # Gatilho Inteligente: Só liga quando a esteira "CI" terminar
  workflow_run:
    workflows: ["CI - Code Quality & Security"]
    types:
      - completed

jobs:
  deploy:
    name: Atualizar Servidor e Reiniciar
    runs-on: self-hosted
    # Trava de Segurança Final: Só roda se o CI passou (ficou verde)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Puxar o código mais recente
        uses: actions/checkout@v4

      - name: Criar arquivo .env automaticamente
        run: |
          echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" > .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_USE_TLS=${{ secrets.MAIL_USE_TLS }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env

      - name: Preparar Ambiente Virtual e Dependências
        run: |
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install -r requirements.txt
          pip install gunicorn
      
      - name: Ajustar Permissões para o usuário trap
        run: |
          sudo chown -R trap:trap .
      
      - name: Reiniciar o serviço da aplicação
        run: |
          sudo /usr/bin/systemctl restart ia-sdlc.service