name: CD - Deploy no Debian

on:
  push:
    branches:
      - main # Gatilho: Só roda quando o código vai para a branch principal

jobs:
  deploy:
    name: Atualizar Servidor e Reiniciar
    runs-on: self-hosted # Destino: O seu servidor Debian
    steps:
      - name: Puxar o código mais recente
        uses: actions/checkout@v4 # Baixa os arquivos do Git

      - name: Criar arquivo .env automaticamente
        run: |
          echo "FLASK_SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" > .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "MAIL_SERVER=${{ secrets.MAIL_SERVER }}" >> .env
          echo "MAIL_PORT=${{ secrets.MAIL_PORT }}" >> .env
          echo "MAIL_USE_TLS=${{ secrets.MAIL_USE_TLS }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_USERNAME }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}" >> .env

      - name: Preparar Ambiente Virtual e Dependências
        run: |
          # Se a pasta venv não existir, cria ela
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          # Ativa o ambiente e instala tudo
          source venv/bin/activate
          pip install -r requirements.txt
          pip install gunicorn # Garante que o motor do site esteja presente
      
      - name: Ajustar Permissões para o usuário trap
        run: |
          sudo chown -R trap:trap .
      
      - name: Reiniciar o serviço da aplicação
        run: |
          # Comando para o Linux carregar o código novo
          sudo /usr/bin/systemctl restart ia-sdlc.service